name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build backend
      working-directory: ./spillway
      run: mvn clean package -DskipTests
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build frontend
      working-directory: ./spillway-frontend
      run: |
        npm ci
        npm run build
        
    - name: Package application
      run: |
        mkdir -p release
        cp spillway/target/*.jar release/
        cd spillway-frontend/dist && tar czf ../../release/frontend.tar.gz * && cd ../..
        cd release && tar czf ../spillway-${{ github.ref_name }}.tar.gz * && cd ..
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          spillway-${{ github.ref_name }}.tar.gz
          release/*.jar
          release/frontend.tar.gz
        generate_release_notes: true
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./spillway
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest