FROM maven:3-eclipse-temurin-21

# Install FFmpeg with hardware acceleration support
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    vainfo \
    intel-media-va-driver-non-free \
    i965-va-driver \
    mesa-va-drivers \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# For NVIDIA GPU support (optional)
# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility

WORKDIR /app

# Copy the pom.xml file
COPY pom.xml .

# Cache dependencies
RUN mvn dependency:go-offline

EXPOSE 8081
ENV MAVEN_CONFIG=/root/.m2

# Start the application in development mode
CMD ["mvn", "spring-boot:run"]