version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spillway
      MYSQL_USER: spillway
      MYSQL_PASSWORD: spillway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
  
  spillway:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to report healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spillway?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: spillway
      SPRING_DATASOURCE_PASSWORD: spillway
      VIDEO_ENCODING_USE_HARDWARE_ACCELERATION: "true"
      VIDEO_ENCODING_HARDWARE_ACCELERATOR: "qsv"
    volumes:
      - ./content:/app/content
      - /dev/dri:/dev/dri  # Give access to Intel GPU
    devices:
      - /dev/dri:/dev/dri  # Map Intel GPU device

volumes:
  mysql_data: