version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spillway
      MYSQL_USER: spillway
      MYSQL_PASSWORD: spillway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - spillway-dev
  
  spillway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spillway?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: spillway
      SPRING_DATASOURCE_PASSWORD: spillway
      SPRING_DEVTOOLS_REMOTE_SECRET: mysecret
      # Disable hardware acceleration
      VIDEO_ENCODING_ENABLE_HW_ACCEL: false
    volumes:
      - ./:/app
      - maven-repo:/root/.m2
      - ./content:/app/content
      - ./temp:/app/temp
      - /app/target
    networks:
      - spillway-dev

networks:
  spillway-dev:
    driver: bridge

volumes:
  mysql_data_dev:
  maven-repo: