version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spillway
      MYSQL_USER: spillway
      MYSQL_PASSWORD: spillway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  spillway:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spillway?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: spillway
      SPRING_DATASOURCE_PASSWORD: spillway
    volumes:
      - ./content:/content

volumes:
  mysql_data: