FROM maven:3-eclipse-temurin-24-alpine@sha256:64f4ac33351e932d931bfe62cba7fcc320317a7d27c3154b6fb120111241efb2

# Install FFmpeg with basic support (no hardware acceleration in dev mode)
RUN apk add --no-cache ffmpeg

WORKDIR /app

# Copy the pom.xml file
COPY pom.xml .

# This is a separate step to cache the dependencies
RUN mvn dependency:go-offline

# The application will be mounted to /app, so we don't need to copy source

EXPOSE 8081
ENV MAVEN_CONFIG=/root/.m2

# Start the application in development mode
CMD ["mvn", "spring-boot:run"]