name: Backend CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'spillway/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'spillway/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      working-directory: ./spillway
      run: mvn clean install -DskipTests
    
    - name: Run unit tests
      working-directory: ./spillway
      run: mvn test
      
    - name: Package application
      working-directory: ./spillway
      run: mvn package -DskipTests
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: spillway-jar
        path: spillway/target/*.jar
        retention-days: 7

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: spillway-jar
        path: spillway/target/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./spillway
        file: ./spillway/Dockerfile
        push: false
        tags: spillway:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max