name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: CD into project directory
      run: cd ${{ github.workspace }}/spillway && ls
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spillway:$(date +%s)